# Generated by Django 2.0 on 2018-03-08 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0047_auto_20180308_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shq_id', models.IntegerField(verbose_name='生活圈ID')),
                ('area', models.CharField(max_length=32, verbose_name='地区名')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.App')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='搜群关键词')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, verbose_name='搜索词')),
                ('group_increment', models.IntegerField(default=0, verbose_name='群增量')),
                ('group_user_increment', models.IntegerField(default=0, verbose_name='群人数增量')),
                ('search_count', models.IntegerField(default=0, verbose_name='搜索次数')),
                ('status', models.IntegerField(default=0, help_text='0 - 使用中 1 - 已禁用', verbose_name='状态')),
                ('last_time', models.DateTimeField(blank=True, null=True, verbose_name='最近一次的搜索时间')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.Area')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.Keyword')),
            ],
        ),
    ]
