# Generated by Django 2.0 on 2018-03-29 05:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_auto_20180329_1350'),
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField(default=datetime.time(8, 0), verbose_name='上班时间')),
                ('closing_time', models.TimeField(default=datetime.time(20, 0), verbose_name='下班时间')),
                ('max_num_of_apply', models.IntegerField(default=3, verbose_name='最大加群数/天·QQ')),
                ('shortest_interval_apply_of_device', models.IntegerField(default=600, verbose_name='设备的最短间隔加群')),
                ('max_num_of_search', models.IntegerField(default=5, verbose_name='最大查群次数/天·设备')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
        migrations.CreateModel(
            name='OperationDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_apply', models.DateTimeField(blank=True, null=True, verbose_name='最近一次加群的时间')),
                ('today_search', models.IntegerField(default=0, verbose_name='今日查群次数')),
                ('today_statistics', models.IntegerField(default=0, verbose_name='今日统计次数')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.PhoneDevice')),
            ],
        ),
        migrations.CreateModel(
            name='OperationSnsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_apply', models.IntegerField(default=0, verbose_name='今日加群数')),
                ('sns_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SnsUser')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_start_time', models.DateTimeField(blank=True, null=True, verbose_name='预计执行时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.PhoneDevice', verbose_name='设备')),
                ('sns_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.SnsUser', verbose_name='帐号')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SnsTaskType', verbose_name='任务类型')),
            ],
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('status', models.IntegerField(default=0, help_text='0 - 正在/继续执行，1 - 完成，-1 - 中断，-2 - 打断', verbose_name='状态')),
                ('result', models.CharField(blank=True, max_length=255, null=True, verbose_name='结果')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.PhoneDevice')),
                ('sns_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.SnsUser')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SnsTaskType')),
            ],
        ),
    ]
