# Generated by Django 2.0 on 2018-06-28 05:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0084_custompush'),
        ('robot', '0002_config_operationdevice_operationsnsuser_scheduledtasks_tasklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.PhoneDevice')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.SnsGroup')),
                ('sns_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.SnsUser')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.PhoneDevice')),
                ('sns_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.SnsUser')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SnsTaskType')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(default=0, help_text='0 - 正在/继续执行，1 - 完成，-1 - 中断，-2 - 打断')),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.PhoneDevice')),
                ('sns_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.SnsUser')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SnsTaskType')),
            ],
        ),
        migrations.RemoveField(
            model_name='area',
            name='app',
        ),
        migrations.RemoveField(
            model_name='operationdevice',
            name='device',
        ),
        migrations.RemoveField(
            model_name='operationsnsuser',
            name='sns_user',
        ),
        migrations.RemoveField(
            model_name='scheduledtasks',
            name='device',
        ),
        migrations.RemoveField(
            model_name='scheduledtasks',
            name='sns_user',
        ),
        migrations.RemoveField(
            model_name='scheduledtasks',
            name='type',
        ),
        migrations.RemoveField(
            model_name='search',
            name='area',
        ),
        migrations.RemoveField(
            model_name='search',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='device',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='sns_user',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='type',
        ),
        migrations.RemoveField(
            model_name='config',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='config',
            name='id',
        ),
        migrations.RemoveField(
            model_name='config',
            name='max_num_of_apply',
        ),
        migrations.RemoveField(
            model_name='config',
            name='max_num_of_search',
        ),
        migrations.RemoveField(
            model_name='config',
            name='opening_time',
        ),
        migrations.RemoveField(
            model_name='config',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='config',
            name='shortest_interval_apply_of_device',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='id',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='isDelete',
        ),
        migrations.AddField(
            model_name='config',
            name='apply_interval',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='config',
            name='apply_max',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='config',
            name='from_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='config',
            name='search_max',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='config',
            name='to_time',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AddField(
            model_name='config',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='keyword',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='关键词'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='OperationDevice',
        ),
        migrations.DeleteModel(
            name='OperationSnsUser',
        ),
        migrations.DeleteModel(
            name='ScheduledTasks',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
        migrations.DeleteModel(
            name='TaskLog',
        ),
        migrations.AddField(
            model_name='eventlog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.Task'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SnsTaskType'),
        ),
    ]
