# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('app_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=32, verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名字')),
                ('cutt_user_id', models.IntegerField(verbose_name='生活圈用户ID')),
                ('memo', models.CharField(max_length=50, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='编号')),
                ('phone_num', models.CharField(max_length=20, verbose_name='手机号')),
                ('type', models.IntegerField(default=1, help_text='0 - 手机，1 - 虚拟机', verbose_name='类型')),
                ('model', models.CharField(max_length=20, verbose_name='型号')),
                ('system', models.CharField(max_length=50, verbose_name='系统和版本')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='SnsGroup',
            fields=[
                ('group_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='群ID')),
                ('type', models.IntegerField(default=0, verbose_name='类型')),
                ('group_name', models.CharField(max_length=50, verbose_name='群名')),
                ('group_user_count', models.IntegerField(default=0, verbose_name='群用户数')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='SnsGroupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=50, verbose_name='昵称')),
                ('title', models.CharField(max_length=20, verbose_name='头衔')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SnsGroup', verbose_name='群')),
            ],
        ),
        migrations.CreateModel(
            name='SnsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='显示名')),
                ('type', models.IntegerField(verbose_name='类型')),
                ('login_name', models.CharField(max_length=30, verbose_name='登录名')),
                ('passwd', models.CharField(max_length=30, verbose_name='密码')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('phone', models.CharField(max_length=30, verbose_name='电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('bot_login_token', models.BinaryField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.App', verbose_name='生活圈')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.PhoneDevice', verbose_name='设备')),
            ],
        ),
        migrations.CreateModel(
            name='SnsUserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=50, verbose_name='备注名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('active', models.IntegerField(default=0, verbose_name='可用')),
                ('last_post_at', models.DateTimeField(null=True, verbose_name='最后分发时间')),
                ('sns_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SnsGroup', verbose_name='群')),
                ('sns_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SnsUser', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='SnsUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0, help_text='0 - QQ 1 - 微信')),
                ('uin', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('nick', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=255)),
                ('memo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('passwd', models.CharField(max_length=50, verbose_name='密码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('memo', models.CharField(max_length=255)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
        migrations.AddField(
            model_name='snsuser',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.User', verbose_name='所有者'),
        ),
        migrations.AddField(
            model_name='snsgroupuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SnsUserInfo', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='phonedevice',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.User', verbose_name='所有者'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User', verbose_name='属于'),
        ),
    ]
