# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnsGroupSplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
        ),
        migrations.AlterModelOptions(
            name='app',
            options={'verbose_name': '生活圈', 'verbose_name_plural': ' 生活圈列表'},
        ),
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'APP马甲', 'verbose_name_plural': ' APP马甲列表'},
        ),
        migrations.AlterModelOptions(
            name='phonedevice',
            options={'verbose_name': '手机', 'verbose_name_plural': ' 手机列表'},
        ),
        migrations.AlterModelOptions(
            name='snsgroup',
            options={'verbose_name': '群', 'verbose_name_plural': '群列表'},
        ),
        migrations.AlterModelOptions(
            name='snsuser',
            options={'verbose_name': '社交账号', 'verbose_name_plural': ' 社交账号列表'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '员工', 'verbose_name_plural': ' 员工列表'},
        ),
        migrations.AddField(
            model_name='user',
            name='app',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.App', verbose_name='生活圈'),
        ),
        migrations.AlterField(
            model_name='phonedevice',
            name='type',
            field=models.IntegerField(default=0, help_text='0 - 手机，1 - 虚拟机', verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='snsgroup',
            name='status',
            field=models.IntegerField(default=0, help_text='0 - 未使用 1 - 已分配 -1 - 忽略', verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='snsgroup',
            name='type',
            field=models.IntegerField(default=0, help_text='0 - QQ 1 - 微信', verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='snsuser',
            name='type',
            field=models.IntegerField(default=0, help_text='0 - QQ 1 - 微信', verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='snsgroupsplit',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SnsGroup', verbose_name='群'),
        ),
        migrations.AddField(
            model_name='snsgroupsplit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User', verbose_name='推广人'),
        ),
    ]
