# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170818_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='snsgroup',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.App', verbose_name='生活圈'),
        ),
    ]
