# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_snsgroup_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='snsgroupsplit',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.PhoneDevice', verbose_name='设备'),
        ),
    ]
