# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_snsgroupsplit_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnsGroupLost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, help_text='0 - 未处理, 1 - 已处理', verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SnsGroup', verbose_name='群')),
                ('sns_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SnsUser', verbose_name='账号')),
            ],
        ),
        migrations.AlterField(
            model_name='phonedevice',
            name='model',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='phonedevice',
            name='system',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='系统和版本'),
        ),
        migrations.AlterField(
            model_name='snsusergroup',
            name='nick_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备注名'),
        ),
    ]
