# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20170831_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(default=0, help_text='0-组员 1-组长'),
        ),
    ]
