# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='snstasktype',
            name='memo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
