# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_snstask_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='snstask',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
        ),
    ]
