# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_snstask_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicefile',
            name='device_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.SnsTaskDevice'),
        ),
        migrations.AddField(
            model_name='devicefile',
            name='file_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
