# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20170907_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='type',
            field=models.IntegerField(default=0, help_text='0:qq分享 1:微信分享 2:其他', verbose_name='类型'),
        ),
    ]
