# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_appuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='cutt_user_id',
            field=models.BigIntegerField(verbose_name='生活圈用户ID'),
        ),
    ]
