# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20170913_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnsApplyTaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memo', models.CharField(max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SnsUser')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.PhoneDevice')),
                ('device_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.SnsTaskDevice')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SnsGroup')),
            ],
        ),
        migrations.CreateModel(
            name='UserAuthApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.App')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
    ]
