# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20170913_2143'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='snsusergroup',
            unique_together=set([('sns_group', 'sns_user')]),
        ),
    ]
