# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20170916_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='snsgroupsplit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='snsgroupsplit',
            name='status',
            field=models.IntegerField(default=0, help_text='0 默认 1 已发送 2 已申请 3 已通过', verbose_name='状态'),
        ),
    ]
