# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_snsapplytasklog_userauthapp'),
        ('backend', '0015_auto_20170917_1617'),
    ]

    operations = [
    ]
