# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_merge_20170918_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_route', models.CharField(max_length=80)),
                ('menu_name', models.CharField(max_length=20)),
                ('menu_category', models.CharField(max_length=20)),
                ('menu_icon', models.CharField(max_length=32)),
                ('show_order', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemPerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.MenuItem')),
            ],
        ),
        migrations.RenameField(
            model_name='userauthapp',
            old_name='App',
            new_name='app',
        ),
    ]
