# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20170918_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDelegate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegate', to='backend.User')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='backend.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userdelegate',
            unique_together=set([('owner', 'delegate')]),
        ),
    ]
