# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_disttasklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipItem',
            fields=[
                ('clipId', models.IntegerField()),
                ('itemId', models.IntegerField(primary_key=True, serialize=False)),
                ('articleId', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'clip_ClipItem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerClipArticle',
            fields=[
                ('articleId', models.IntegerField(primary_key=True, serialize=False)),
                ('partnerId', models.IntegerField()),
            ],
            options={
                'db_table': 'partner_PartnerClipArticle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShareArticleLog',
            fields=[
                ('partnerId', models.IntegerField()),
                ('deviceUserId', models.IntegerField()),
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('target', models.IntegerField()),
                ('type', models.IntegerField()),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'datasystem_ShareArticleLog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZhiyueUser',
            fields=[
                ('appId', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pojo_ZhiyueUser',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='snsgroup',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.User', verbose_name='爬群用户'),
        ),
    ]
