# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_auto_20171012_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='snsapplytasklog',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
