# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='snstask',
            name='finish_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='snstask',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
