# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_auto_20171017_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceUser',
            fields=[
                ('partnerId', models.IntegerField()),
                ('createTime', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('deviceUserId', models.IntegerField(primary_key=True, serialize=False)),
                ('deviceId', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('deviceType', models.CharField(max_length=255)),
                ('extStr', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('sourceItemId', models.IntegerField()),
                ('sourceUserId', models.IntegerField()),
            ],
            options={
                'db_table': 'datasystem_DeviceUser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeizhanCount',
            fields=[
                ('partnerId', models.IntegerField(primary_key=True, serialize=False)),
                ('pcPV', models.IntegerField()),
                ('mobilePV', models.IntegerField()),
                ('downPage', models.IntegerField()),
                ('appUser', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('weizhanPv', models.IntegerField()),
            ],
            options={
                'db_table': 'datasystem_WeizhanCount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskWorkingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SnsUser')),
                ('device_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SnsTaskDevice')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='taskworkinglog',
            unique_together=set([('device_task', 'account')]),
        ),
    ]
