# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_adminpartneruser_highvalueuser_userdailystat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDailyStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.CharField(max_length=20)),
                ('qq_pv', models.IntegerField()),
                ('wx_pv', models.IntegerField()),
                ('qq_down', models.IntegerField()),
                ('wx_down', models.IntegerField()),
                ('qq_install', models.IntegerField()),
                ('wx_install', models.IntegerField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.App')),
            ],
        ),
    ]
