# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_appdailystat'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTaskData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lines', models.TextField()),
                ('device_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SnsTaskDevice')),
            ],
        ),
        migrations.AlterField(
            model_name='snsgroup',
            name='group_id',
            field=models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='群ID'),
        ),
        migrations.AlterField(
            model_name='snsuser',
            name='login_name',
            field=models.CharField(max_length=80, verbose_name='登录名'),
        ),
    ]
