# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_auto_20171027_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushMessage',
            fields=[
                ('messageId', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('appId', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('createTime', models.DateTimeField()),
                ('pushTime', models.DateTimeField()),
                ('articleId', models.IntegerField()),
            ],
            options={
                'db_table': 'push_PushMessage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SnsUserKickLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SnsTaskDevice')),
                ('sns_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SnsUser')),
            ],
        ),
    ]
