# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_pushmessage_snsuserkicklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iphone', models.IntegerField()),
                ('android', models.IntegerField()),
                ('total', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.App')),
            ],
        ),
    ]
