# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_dailyactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('delete_flag', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField()),
                ('started_at', models.DateTimeField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.App')),
            ],
        ),
        migrations.CreateModel(
            name='DistArticleStatDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('qq_pv', models.IntegerField()),
                ('wx_pv', models.IntegerField()),
                ('qq_down', models.IntegerField()),
                ('wx_down', models.IntegerField()),
                ('qq_user', models.IntegerField()),
                ('wx_user', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.DistArticle')),
            ],
        ),
    ]
