# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_distarticle_distarticlestatdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistArticleStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qq_pv', models.IntegerField()),
                ('wx_pv', models.IntegerField()),
                ('qq_down', models.IntegerField()),
                ('wx_down', models.IntegerField()),
                ('qq_user', models.IntegerField()),
                ('wx_user', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.DistArticle')),
            ],
        ),
        migrations.AlterField(
            model_name='distarticlestatdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
