# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_auto_20171107_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponInst',
            fields=[
                ('partnerId', models.IntegerField()),
                ('couponId', models.IntegerField()),
                ('couponNum', models.IntegerField(primary_key=True, serialize=False)),
                ('userId', models.BigIntegerField()),
                ('useDate', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'partner_CouponInst',
            },
        ),
        migrations.CreateModel(
            name='ShopCouponStatSum',
            fields=[
                ('partnerId', models.IntegerField()),
                ('ownerName', models.CharField(max_length=50)),
                ('shopName', models.CharField(max_length=50)),
                ('useDate', models.CharField(max_length=10)),
                ('ownerId', models.IntegerField(primary_key=True, serialize=False)),
                ('useNum', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'partner_ShopCouponStatSum',
            },
        ),
    ]
