# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_couponinst_shopcouponstatsum'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMore',
            fields=[
                ('itemId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('appId', models.IntegerField()),
                ('title', models.CharField(verbose_name=80)),
                ('content', models.CharField(verbose_name=255)),
                ('createTime', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'partner_ItemMore',
            },
        ),
        migrations.AddField(
            model_name='snsuser',
            name='provider',
            field=models.CharField(default='qq', max_length=10),
        ),
    ]
