# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_auto_20171130_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRemain',
            fields=[
                ('bizType', models.IntegerField()),
                ('dateType', models.IntegerField()),
                ('clipId', models.IntegerField()),
                ('day', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=20)),
                ('platform', models.CharField(max_length=10)),
                ('partnerId', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'report_UserRemain',
            },
        ),
        migrations.AddField(
            model_name='snstask',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.DistArticle'),
        ),
    ]
