# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_auto_20171205_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRewardHistory',
            fields=[
                ('partnerId', models.IntegerField()),
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('createTime', models.DateTimeField()),
                ('source', models.CharField(max_length=20)),
                ('type', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'partner_UserRewardHistory',
            },
        ),
        migrations.AlterModelOptions(
            name='userremain',
            options={},
        ),
        migrations.AddField(
            model_name='distarticlestat',
            name='dist_qq_phone_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='distarticlestat',
            name='dist_qq_user_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='distarticlestat',
            name='dist_qun_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='distarticlestat',
            name='dist_qun_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='distarticlestat',
            name='dist_wx_phone_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='distarticlestat',
            name='dist_wx_user_count',
            field=models.IntegerField(default=0),
        ),
    ]
