# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_auto_20171205_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponPmSentInfo',
            fields=[
                ('messageId', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('partnerId', models.IntegerField()),
                ('createTime', models.DateTimeField()),
                ('message', models.CharField(max_length=80)),
                ('status', models.IntegerField()),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'partner_CouponPmSentInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WxDistLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('user_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.SnsTaskDevice')),
            ],
        ),
    ]
