# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-18 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_couponpmsentinfo_wxdistlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='distarticle',
            name='last_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='distarticle',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
