# Generated by Django 2.0 on 2017-12-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_auto_20171218_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConstants',
            fields=[
                ('type', models.IntegerField()),
                ('constType', models.CharField(max_length=64)),
                ('constId', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('constName', models.CharField(max_length=255)),
                ('memo', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'partner_AppConstants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CouponDailyStatInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnerId', models.IntegerField()),
                ('statDate', models.DateField(auto_now_add=True)),
                ('total', models.IntegerField()),
                ('active', models.IntegerField()),
                ('open', models.IntegerField()),
                ('remainDay', models.IntegerField()),
                ('remainOpen', models.IntegerField()),
                ('remainNotOpen', models.IntegerField()),
            ],
            options={
                'db_table': 'partner_CouponStatInfo',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='snsgroupsplit',
            name='apply_count',
            field=models.IntegerField(default=0),
        ),
    ]
