# Generated by Django 2.0 on 2018-03-08 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_auto_20171221_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='self_qun',
            field=models.IntegerField(default=1, help_text='0 - 查群的结果平均分配给所有人，1 - 查群的结果分配给自己', verbose_name='自行导入群'),
        ),
        migrations.AlterField(
            model_name='devicefile',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.PhoneDevice', verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='devicefile',
            name='file_name',
            field=models.CharField(max_length=50, null=True, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='devicefile',
            name='qiniu_key',
            field=models.CharField(max_length=255, verbose_name='保存到文件服务器的名字'),
        ),
        migrations.AlterField(
            model_name='devicefile',
            name='type',
            field=models.CharField(help_text='日志log, 截图image', max_length=20, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='distarticle',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='文章类型'),
        ),
        migrations.AlterField(
            model_name='distarticle',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='distarticle',
            name='delete_flag',
            field=models.IntegerField(default=0, verbose_name='是否已删除'),
        ),
        migrations.AlterField(
            model_name='distarticle',
            name='item_id',
            field=models.IntegerField(unique=True, verbose_name='cutt内部文章ID'),
        ),
        migrations.AlterField(
            model_name='distarticle',
            name='last_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后一次分发时间'),
        ),
        migrations.AlterField(
            model_name='distarticle',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='第一次分发时间'),
        ),
        migrations.AlterField(
            model_name='distarticle',
            name='title',
            field=models.CharField(max_length=255, verbose_name='文章标题'),
        ),
        migrations.AlterField(
            model_name='distarticlestat',
            name='dist_qq_phone_count',
            field=models.IntegerField(default=0, verbose_name='分发的QQ手机数'),
        ),
        migrations.AlterField(
            model_name='distarticlestat',
            name='dist_qq_user_count',
            field=models.IntegerField(default=0, verbose_name='分发的QQ数'),
        ),
        migrations.AlterField(
            model_name='distarticlestat',
            name='dist_qun_count',
            field=models.IntegerField(default=0, verbose_name='群数'),
        ),
        migrations.AlterField(
            model_name='distarticlestat',
            name='dist_qun_user',
            field=models.IntegerField(default=0, verbose_name='群用户数'),
        ),
        migrations.AlterField(
            model_name='distarticlestat',
            name='dist_wx_phone_count',
            field=models.IntegerField(default=0, verbose_name='分发的微信手机数'),
        ),
        migrations.AlterField(
            model_name='distarticlestat',
            name='dist_wx_user_count',
            field=models.IntegerField(default=0, verbose_name='分发的微信数'),
        ),
        migrations.AlterField(
            model_name='distarticlestat',
            name='qq_down',
            field=models.IntegerField(verbose_name='下载页'),
        ),
        migrations.AlterField(
            model_name='distarticlestat',
            name='qq_pv',
            field=models.IntegerField(verbose_name='PV'),
        ),
        migrations.AlterField(
            model_name='distarticlestat',
            name='qq_user',
            field=models.IntegerField(verbose_name='关联安装'),
        ),
        migrations.AlterField(
            model_name='distarticlestatdetail',
            name='qq_user',
            field=models.IntegerField(verbose_name='关联安装数'),
        ),
        migrations.AlterField(
            model_name='disttasklog',
            name='success',
            field=models.IntegerField(verbose_name='1 成功或 0 失败'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_category',
            field=models.CharField(max_length=20, verbose_name='类型（目录、功能）'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_icon',
            field=models.CharField(max_length=32, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_name',
            field=models.CharField(max_length=20, verbose_name='菜单的名字'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_route',
            field=models.CharField(max_length=80, verbose_name='菜单的英文名'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='show_order',
            field=models.IntegerField(default=0, verbose_name='显示顺序'),
        ),
        migrations.AlterField(
            model_name='menuitemperm',
            name='role',
            field=models.IntegerField(default=0, help_text='0 - 所有人 1 - 组长 2 - 管理', verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='snsapplytasklog',
            name='memo',
            field=models.CharField(max_length=30, verbose_name='结果文字'),
        ),
        migrations.AlterField(
            model_name='snsgroup',
            name='status',
            field=models.IntegerField(default=0, help_text='0 - 未使用 1 - 已分配 -1 - 忽略 2 - 已加入', verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='snstask',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.DistArticle', verbose_name='对应的文章'),
        ),
        migrations.AlterField(
            model_name='snstask',
            name='data',
            field=models.TextField(blank=True, null=True, verbose_name='参数'),
        ),
        migrations.AlterField(
            model_name='snstask',
            name='finish_at',
            field=models.DateTimeField(null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='snstask',
            name='schedule_at',
            field=models.DateTimeField(null=True, verbose_name='定时发送的时间'),
        ),
        migrations.AlterField(
            model_name='snstask',
            name='started_at',
            field=models.DateTimeField(null=True, verbose_name='启动时间'),
        ),
        migrations.AlterField(
            model_name='snstask',
            name='status',
            field=models.IntegerField(default=0, help_text='0 - 初始  1 - 进行中  2 - 已完成', verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='snstaskdevice',
            name='data',
            field=models.TextField(blank=True, null=True, verbose_name='参数'),
        ),
        migrations.AlterField(
            model_name='snstaskdevice',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='进度'),
        ),
        migrations.AlterField(
            model_name='snstaskdevice',
            name='status',
            field=models.IntegerField(default=0, help_text='0 - 初始  1 - 进行中  2 - 已完成 取消 暂停'),
        ),
        migrations.AlterField(
            model_name='snsuser',
            name='bot_login_token',
            field=models.BinaryField(blank=True, null=True, verbose_name='字段未使用'),
        ),
        migrations.AlterField(
            model_name='snsuser',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.PhoneDevice', verbose_name='登录的设备'),
        ),
        migrations.AlterField(
            model_name='snsuser',
            name='dist',
            field=models.IntegerField(default=1, verbose_name='用于分发'),
        ),
        migrations.AlterField(
            model_name='snsuser',
            name='friend',
            field=models.IntegerField(default=1, verbose_name='可加群'),
        ),
        migrations.AlterField(
            model_name='snsuser',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='绑定的电话号码'),
        ),
        migrations.AlterField(
            model_name='snsuser',
            name='provider',
            field=models.CharField(default='qq', max_length=10, verbose_name='登录的软件(qq、tim)'),
        ),
        migrations.AlterField(
            model_name='snsuser',
            name='search',
            field=models.IntegerField(default=0, verbose_name='可查群'),
        ),
        migrations.AlterField(
            model_name='snsuser',
            name='status',
            field=models.IntegerField(default=0, help_text='0 - 正常 -1 弃用的', verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='snsusergroup',
            name='status',
            field=models.IntegerField(default=0, help_text='-1 - 被踢', verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notify',
            field=models.IntegerField(default=0, help_text='是否接受钉钉通知', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(default=0, help_text='0 - 正常分发的操作者， 1 - 不分发的系统用户', verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='userdailystat',
            name='qq_down',
            field=models.IntegerField(verbose_name='QQ 下载页打开次数'),
        ),
        migrations.AlterField(
            model_name='userdailystat',
            name='qq_install',
            field=models.IntegerField(verbose_name='QQ安装数'),
        ),
        migrations.AlterField(
            model_name='userdailystat',
            name='qq_pv',
            field=models.IntegerField(verbose_name='QQ PV'),
        ),
        migrations.AlterField(
            model_name='userdailystat',
            name='report_date',
            field=models.CharField(max_length=20, verbose_name='统计日期'),
        ),
        migrations.AlterField(
            model_name='userdailystat',
            name='wx_down',
            field=models.IntegerField(verbose_name='微信下载页打开次数'),
        ),
        migrations.AlterField(
            model_name='userdailystat',
            name='wx_install',
            field=models.IntegerField(verbose_name='微信安装数'),
        ),
        migrations.AlterField(
            model_name='userdailystat',
            name='wx_pv',
            field=models.IntegerField(verbose_name='微信 PV'),
        ),
    ]
