# Generated by Django 2.0 on 2018-03-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_auto_20180308_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='snsusergroup',
            name='kick_times',
            field=models.IntegerField(default=0, verbose_name='被踢的次数'),
        ),
    ]
