# Generated by Django 2.0 on 2018-03-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0048_snsusergroup_kick_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='snsgroup',
            name='kick_times',
            field=models.IntegerField(default=0, verbose_name='被踢的次数'),
        ),
    ]
