# Generated by Django 2.0 on 2018-03-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_snsgroup_kick_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineDailyStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField()),
                ('stat_date', models.CharField(max_length=12)),
                ('user_num', models.IntegerField(verbose_name='新增')),
                ('user_cost', models.IntegerField(verbose_name='花费')),
                ('remain', models.IntegerField(default=0, verbose_name='留存')),
                ('user_bonus_num', models.IntegerField(default=0, verbose_name='领取红包数')),
                ('bonus_cost', models.IntegerField(default=0, verbose_name='红包奖励')),
                ('bonus_cash', models.IntegerField(default=0, verbose_name='红包提取')),
                ('total_cost', models.IntegerField(default=0, verbose_name='总花费')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='推广消耗'),
        ),
        migrations.AddField(
            model_name='app',
            name='offline',
            field=models.IntegerField(default=0, verbose_name='是否在地推'),
        ),
        migrations.AddField(
            model_name='app',
            name='price',
            field=models.FloatField(default=0, verbose_name='推广单价'),
        ),
    ]
