# Generated by Django 2.0 on 2018-03-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_auto_20180312_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinedailystat',
            name='user_cost',
            field=models.IntegerField(default=0, verbose_name='花费'),
        ),
        migrations.AlterField(
            model_name='offlinedailystat',
            name='user_num',
            field=models.IntegerField(default=0, verbose_name='新增'),
        ),
    ]
