# Generated by Django 2.0 on 2018-03-20 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_auto_20180313_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppWeeklyResourceStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(auto_now_add=True)),
                ('qq_cnt', models.IntegerField(verbose_name='QQ分发数')),
                ('wx_cnt', models.IntegerField(verbose_name='微信分发数')),
                ('phone_cnt', models.IntegerField(verbose_name='手机个数')),
                ('qq_acc_cnt', models.IntegerField(verbose_name='QQ账号数')),
                ('qq_group_cnt', models.IntegerField(verbose_name='QQ群数')),
                ('wx_group_cnt', models.IntegerField(verbose_name='微信群数')),
                ('qq_uniq_group_cnt', models.IntegerField(verbose_name='排重后')),
                ('wx_uniq_group_cnt', models.IntegerField()),
                ('qq_apply_cnt', models.IntegerField(verbose_name='QQ申请数')),
                ('qq_lost_cnt', models.IntegerField(verbose_name='QQ群被踢数')),
                ('qq_group_new_cnt', models.IntegerField(verbose_name='新群')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.App')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceWeinxinGroupLost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='群名')),
                ('member_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.PhoneDevice')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceWeixinGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='群名')),
                ('member_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.PhoneDevice')),
            ],
        ),
        migrations.CreateModel(
            name='UserDailyResourceStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(auto_now_add=True)),
                ('qq_cnt', models.IntegerField()),
                ('wx_cnt', models.IntegerField()),
                ('phone_cnt', models.IntegerField()),
                ('qq_acc_cnt', models.IntegerField()),
                ('qq_group_cnt', models.IntegerField()),
                ('wx_group_cnt', models.IntegerField()),
                ('qq_uniq_group_cnt', models.IntegerField()),
                ('wx_uniq_group_cnt', models.IntegerField()),
                ('qq_apply_cnt', models.IntegerField()),
                ('qq_lost_cnt', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
    ]
