# Generated by Django 2.0 on 2018-03-20 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_appweeklyresourcestat_deviceweinxingrouplost_deviceweixingroup_userdailyresourcestat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDailyResourceStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(auto_now_add=True)),
                ('qq_cnt', models.IntegerField(verbose_name='QQ分发数')),
                ('wx_cnt', models.IntegerField(verbose_name='微信分发数')),
                ('phone_cnt', models.IntegerField(verbose_name='手机个数')),
                ('qq_acc_cnt', models.IntegerField(verbose_name='QQ账号数')),
                ('qq_group_cnt', models.IntegerField(verbose_name='QQ群数')),
                ('wx_group_cnt', models.IntegerField(verbose_name='微信群数')),
                ('qq_uniq_group_cnt', models.IntegerField(verbose_name='排重后')),
                ('wx_uniq_group_cnt', models.IntegerField()),
                ('qq_apply_cnt', models.IntegerField(verbose_name='QQ申请数')),
                ('qq_lost_cnt', models.IntegerField(verbose_name='QQ群被踢数')),
                ('wx_lost_cnt', models.IntegerField()),
                ('qq_group_new_cnt', models.IntegerField(verbose_name='新群')),
                ('qq_group_total', models.IntegerField()),
                ('qq_members', models.IntegerField(default=0)),
                ('wx_members', models.IntegerField(default=0)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.App')),
            ],
        ),
        migrations.CreateModel(
            name='AppWeeklyStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qq_pv', models.IntegerField()),
                ('qq_users', models.IntegerField()),
                ('wx_pv', models.IntegerField()),
                ('wx_users', models.IntegerField()),
                ('operators', models.IntegerField()),
                ('device_cnt', models.IntegerField()),
                ('qq_acc_cnt', models.IntegerField()),
                ('qq_cnt', models.IntegerField(verbose_name='qq分发数')),
                ('wx_cnt', models.IntegerField(verbose_name='微信分发数')),
                ('qq_group_cnt', models.IntegerField()),
                ('wx_group_cnt', models.IntegerField()),
                ('qq_uniq_group_cnt', models.IntegerField()),
                ('wx_uniq_group_cnt', models.IntegerField()),
                ('qq_apply_cnt', models.IntegerField()),
                ('qq_lost_cnt', models.IntegerField()),
                ('qq_group_new_cnt', models.IntegerField(verbose_name='新群')),
                ('qq_group_total', models.IntegerField()),
                ('qq_members', models.IntegerField(default=0)),
                ('wx_members', models.IntegerField(default=0)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.App')),
            ],
        ),
        migrations.RenameModel(
            old_name='DeviceWeinxinGroupLost',
            new_name='DeviceWeixinGroupLost',
        ),
        migrations.RemoveField(
            model_name='appweeklyresourcestat',
            name='app',
        ),
        migrations.AddField(
            model_name='userdailyresourcestat',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.App'),
        ),
        migrations.AddField(
            model_name='userdailyresourcestat',
            name='qq_members',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdailyresourcestat',
            name='wx_lost_cnt',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdailyresourcestat',
            name='wx_members',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdailyresourcestat',
            name='wx_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='AppWeeklyResourceStat',
        ),
    ]
