# Generated by Django 2.0 on 2018-03-22 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_auto_20180320_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDeviceUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('user_id', models.BigIntegerField(unique=True)),
                ('item_id', models.BigIntegerField(default=0)),
                ('type', models.IntegerField(default=0, help_text='0 - QQ, 1 - 微信')),
                ('remain', models.IntegerField(default=0)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.App')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserDailyDeviceUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.CharField(max_length=20, verbose_name='统计日期')),
                ('qq_user_ids', models.TextField()),
                ('wx_user_ids', models.TextField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.App')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
        migrations.AddField(
            model_name='appdailystat',
            name='qq_remain',
            field=models.IntegerField(default=0, verbose_name='次日留存数'),
        ),
        migrations.AddField(
            model_name='appdailystat',
            name='wx_remain',
            field=models.IntegerField(default=0, verbose_name='次日留存数'),
        ),
        migrations.AddField(
            model_name='userdailystat',
            name='qq_remain',
            field=models.IntegerField(default=0, verbose_name='次日留存'),
        ),
        migrations.AddField(
            model_name='userdailystat',
            name='wx_remain',
            field=models.IntegerField(default=0, verbose_name='次日留存'),
        ),
    ]
