# Generated by Django 2.0 on 2018-03-23 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0055_articledailyinfo_runtimedata_weizhanitemview'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledailyinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
        ),
    ]
