# Generated by Django 2.0 on 2018-03-24 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0056_articledailyinfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appweeklystat',
            old_name='device_cnt',
            new_name='wx_user',
        ),
        migrations.RemoveField(
            model_name='appweeklystat',
            name='qq_users',
        ),
        migrations.RemoveField(
            model_name='appweeklystat',
            name='wx_users',
        ),
        migrations.AddField(
            model_name='appweeklystat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appweeklystat',
            name='phone_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appweeklystat',
            name='qq_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appweeklystat',
            name='qq_remain',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appweeklystat',
            name='qq_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appweeklystat',
            name='stat_date',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appweeklystat',
            name='wx_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appweeklystat',
            name='wx_remain',
            field=models.IntegerField(default=0),
        ),
    ]
