# Generated by Django 2.0 on 2018-03-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_auto_20180324_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdeviceuser',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='itemdeviceuser',
            name='ip',
            field=models.CharField(default='', max_length=20),
        ),
    ]
