# Generated by Django 2.0 on 2018-04-01 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_auto_20180329_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_date', models.CharField(max_length=20)),
                ('to_date', models.CharField(max_length=20)),
                ('pv', models.IntegerField(default=0)),
                ('users', models.IntegerField(default=0)),
                ('remains', models.IntegerField(default=0)),
                ('editors', models.CharField(max_length=255)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.App')),
            ],
        ),
    ]
