# Generated by Django 2.0 on 2018-04-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0066_app_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdeviceuser',
            name='cutt_user_id',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
