# Generated by Django 2.0 on 2018-04-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0067_itemdeviceuser_cutt_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='distarticlestat',
            name='qq_remain',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='distarticlestat',
            name='wx_remain',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='distarticlestat',
            name='qq_down',
            field=models.IntegerField(default=0, verbose_name='下载页'),
        ),
        migrations.AlterField(
            model_name='distarticlestat',
            name='qq_pv',
            field=models.IntegerField(default=0, verbose_name='PV'),
        ),
        migrations.AlterField(
            model_name='distarticlestat',
            name='qq_user',
            field=models.IntegerField(default=0, verbose_name='关联安装'),
        ),
        migrations.AlterField(
            model_name='distarticlestat',
            name='wx_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='distarticlestat',
            name='wx_pv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='distarticlestat',
            name='wx_user',
            field=models.IntegerField(default=0),
        ),
    ]
