# Generated by Django 2.0 on 2018-04-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0068_auto_20180410_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRewardGroundHistory',
            fields=[
                ('userId', models.BigIntegerField()),
                ('type', models.IntegerField()),
                ('createTime', models.DateTimeField(primary_key=True, serialize=False)),
                ('partnerId', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'partner_UserRewardGroundHistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WithdrawApply',
            fields=[
                ('partnerId', models.IntegerField()),
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=50)),
                ('finishTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'shop_WithdrawApply',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='offlineuser',
            name='bonus_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offlineuser',
            name='bonus_got',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offlineuser',
            name='bonus_pick',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offlineuser',
            name='bonus_step',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offlineuser',
            name='bonus_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='offlineuser',
            name='bonus_withdraw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offlineuser',
            name='withdraw_time',
            field=models.DateTimeField(null=True),
        ),
    ]
