# Generated by Django 2.0 on 2018-04-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0071_auto_20180418_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdeviceuser',
            name='remain_14',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemdeviceuser',
            name='remain_7',
            field=models.IntegerField(default=0),
        ),
    ]
