# Generated by Django 2.0 on 2018-04-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0072_auto_20180418_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinedailystat',
            name='user_bonus_got',
            field=models.IntegerField(default=0, verbose_name='获得红包数'),
        ),
    ]
