# Generated by Django 2.0 on 2018-04-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0073_offlinedailystat_user_bonus_got'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinedailystat',
            name='user_cash_num',
            field=models.IntegerField(default=0, verbose_name='红包提取个数'),
        ),
    ]
