# Generated by Django 2.0 on 2018-05-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0077_auto_20180503_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceweixingroup',
            name='last_dist_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
