# Generated by Django 2.0 on 2018-05-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0078_deviceweixingroup_last_dist_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledailyinfo',
            name='android_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articledailyinfo',
            name='android_pv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articledailyinfo',
            name='iphone_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articledailyinfo',
            name='iphone_pv',
            field=models.IntegerField(default=0),
        ),
    ]
