# Generated by Django 2.0 on 2018-05-29 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0080_itemdeviceuser_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushAuditLog',
            fields=[
                ('messageId', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('actionTime', models.DateTimeField()),
                ('operator', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=64)),
                ('status', models.IntegerField()),
                ('itemId', models.BigIntegerField()),
                ('pushMessage', models.CharField(max_length=255)),
                ('partnerId', models.BigIntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'cms_PushAuditLog',
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.App'),
        ),
    ]
