# Generated by Django 2.0 on 2018-05-31 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0081_auto_20180529_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteRecord',
            fields=[
                ('userId', models.BigIntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('invitedUserId', models.BigIntegerField(null=True)),
                ('registerTime', models.DateTimeField(null=True)),
                ('status', models.IntegerField(default=0)),
                ('partnerId', models.IntegerField()),
                ('createTime', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_InviteRecord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InviteRewardRecord',
            fields=[
                ('partnerId', models.IntegerField()),
                ('userId', models.BigIntegerField()),
                ('invitedUserId', models.BigIntegerField()),
                ('taskId', models.IntegerField()),
                ('rewardType', models.IntegerField()),
                ('getTime', models.DateTimeField()),
                ('createTime', models.DateTimeField()),
                ('recordId', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_InviteRewardRecord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDeviceHistory',
            fields=[
                ('appId', models.IntegerField()),
                ('userId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('loginTime', models.DateTimeField()),
                ('deviceId', models.CharField(max_length=64)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'partner_UserDeviceHistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InviteUser',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dev_user_id', models.BigIntegerField()),
                ('referer_id', models.BigIntegerField(db_index=True, verbose_name='邀请人')),
                ('user_award', models.IntegerField(default=0)),
                ('refer_award', models.IntegerField(default=0)),
                ('task_success', models.IntegerField(default=0)),
                ('user_withdraw', models.IntegerField()),
                ('refer_withdraw', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('remain', models.IntegerField(default=0)),
                ('ip', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=50)),
                ('location', models.CharField(default='', max_length=100, null=True)),
                ('remain_7', models.IntegerField(default=0)),
                ('remain_14', models.IntegerField(default=0)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.App')),
            ],
        ),
    ]
