# Generated by Django 2.0 on 2018-05-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0082_inviterecord_inviterewardrecord_inviteuser_userdevicehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteuser',
            name='refer_withdraw',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inviteuser',
            name='user_withdraw',
            field=models.IntegerField(default=0),
        ),
    ]
