# Generated by Django 2.0 on 2018-07-09 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0084_custompush'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryTaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=20)),
                ('data', models.TextField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.PhoneDevice')),
            ],
        ),
    ]
