# Generated by Django 2.0 on 2018-07-09 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0085_secondarytasklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonedevice',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.App', verbose_name='所属APP'),
        ),
        migrations.AddField(
            model_name='snsgroupsplit',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.App', verbose_name='所属APP'),
        ),
    ]
