# Generated by Django 2.0 on 2018-08-14 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0090_auto_20180807_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, help_text='\n                                            0-calling创建请求\n                                            1-calling切换到指定QQ\n                                            2-called查看了请求\n                                            3-called返回在线qq号\n                                            4-calling查看了qq号\n                                            5-calling已呼叫\n                                            6-called接到呼叫\n                                            7-calling确认已接\n                                            ')),
                ('change_time', models.DateTimeField(auto_now=True)),
                ('success_or_failure', models.NullBooleanField()),
                ('failure_reason', models.CharField(blank=True, max_length=30, null=True)),
                ('called', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='called', to='backend.PhoneDevice', verbose_name='被叫设备')),
                ('called_qq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='called', to='backend.SnsUser', verbose_name='被叫QQ')),
                ('calling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calling', to='backend.PhoneDevice', verbose_name='主叫设备')),
                ('calling_qq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calling', to='backend.SnsUser', verbose_name='主叫QQ')),
            ],
        ),
        migrations.AddField(
            model_name='itemdeviceuser',
            name='region',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
