# Generated by Django 2.0 on 2018-08-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0091_auto_20180814_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeizhanDownClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField(db_index=True)),
                ('item_id', models.BigIntegerField(db_index=True, default=0)),
                ('type', models.CharField(default='', max_length=30)),
                ('uid', models.BigIntegerField(default=0)),
                ('img', models.CharField(default='', max_length=255)),
                ('href', models.CharField(default='', max_length=255)),
                ('idx', models.IntegerField(default=0)),
                ('tid', models.IntegerField(default=0)),
                ('net', models.CharField(default='WIFI', max_length=10)),
                ('platform', models.CharField(default='android', max_length=20)),
                ('ip', models.CharField(max_length=20)),
                ('uuid', models.CharField(max_length=32)),
                ('ts', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
