# Generated by Django 2.0 on 2018-08-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0092_weizhandownclick'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeizhanClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField(db_index=True)),
                ('item_id', models.BigIntegerField(db_index=True, default=0)),
                ('uid', models.BigIntegerField(default=0)),
                ('ua', models.CharField(max_length=255)),
                ('qq', models.CharField(max_length=20)),
                ('ts2', models.CharField(max_length=20)),
                ('uuid', models.CharField(max_length=32)),
                ('ts', models.DateTimeField(db_index=True)),
                ('platform', models.CharField(max_length=10)),
                ('net', models.CharField(default='WIFI', max_length=10)),
                ('ip', models.CharField(max_length=20)),
                ('from_param', models.CharField(default='', max_length=20)),
                ('is_installed', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='weizhandownclick',
            name='ua',
            field=models.CharField(default='', max_length=255),
        ),
    ]
