# Generated by Django 2.0 on 2018-08-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0093_auto_20180814_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='weizhanclick',
            name='tid',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
