# Generated by Django 2.0 on 2018-08-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0094_weizhanclick_tid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weizhandownclick',
            name='tid',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
