# Generated by Django 2.0 on 2018-08-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0097_auto_20180815_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeizhanClickDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField(db_index=True)),
                ('stat_date', models.CharField(max_length=10)),
                ('item_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('task_id', models.IntegerField(default=0)),
                ('qq_id', models.IntegerField(default=0)),
                ('platform', models.CharField(max_length=10)),
                ('cnt', models.IntegerField(default=0)),
                ('down_page_cnt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WeizhanDlClickDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField(db_index=True)),
                ('stat_date', models.CharField(max_length=10)),
                ('item_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('task_id', models.IntegerField(default=0)),
                ('qq_id', models.IntegerField(default=0)),
                ('platform', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=20)),
                ('cnt', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='weizhanclick',
            name='item_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weizhandownclick',
            name='item_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='weizhandownclick',
            unique_together={('item_id', 'uuid', 'uid', 'task_id')},
        ),
    ]
