# Generated by Django 2.0 on 2018-08-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0098_auto_20180817_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='weizhanclickdaily',
            name='sns_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weizhandlclickdaily',
            name='sns_type',
            field=models.IntegerField(default=0),
        ),
    ]
