# Generated by Django 2.1 on 2018-08-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0100_weizhandownclick_qq'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxdistlog',
            name='dist',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
