# Generated by Django 2.1 on 2018-08-29 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0101_wxdistlog_dist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploader',
            fields=[
                ('imageId', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('userId', models.BigIntegerField()),
                ('partnerId', models.BigIntegerField()),
                ('createTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'cms_ImageUploader',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MpSentItem',
            fields=[
                ('userId', models.BigIntegerField()),
                ('itemId', models.BigIntegerField()),
                ('partnerId', models.IntegerField()),
                ('sentTime', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'partner_MpItemSent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerImage',
            fields=[
                ('imageId', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('partnerId', models.BigIntegerField()),
                ('createTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'partner_PartnerImage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditImage',
            fields=[
                ('image_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('app_id', models.IntegerField()),
                ('user_id', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DingTalkToken',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64)),
                ('memo', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserFollowApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.App')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
    ]
