# Generated by Django 2.1 on 2018-09-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0103_snstaskdevice_pv'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdeviceuser',
            name='view',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
