# Generated by Django 2.0 on 2018-09-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0104_itemdeviceuser_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditimage',
            name='ua',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
