# Generated by Django 2.0 on 2018-09-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0106_auditimage_image_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceUserExtra',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('app_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('ip', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=50)),
                ('location', models.CharField(default='', max_length=100, null=True)),
                ('region', models.CharField(default='', max_length=100)),
                ('view_source_item', models.IntegerField(default=0, verbose_name='是否查看关联安装文章')),
                ('remain', models.IntegerField(default=0)),
                ('area', models.CharField(max_length=20)),
                ('area_type', models.IntegerField(default=0, help_text='0 - 主城区，1 - 县城，2 - 其他')),
                ('platform', models.CharField(help_text='iphone/android', max_length=10)),
                ('lbs_flag', models.IntegerField(default=0, verbose_name='是否打开gps')),
                ('view_items', models.IntegerField(default=0, verbose_name='第一次查看文章次数(30分钟内)')),
                ('open_push', models.IntegerField(default=0, verbose_name='是否打开推送')),
                ('view_push', models.IntegerField(default=0, verbose_name='是否查看推送')),
                ('view_clips', models.IntegerField(default=0, verbose_name='查看的栏目个数')),
                ('sign_on', models.IntegerField(default=0, verbose_name='是否登录')),
                ('open_times', models.IntegerField(default=0, verbose_name='第一天打开APP次数')),
            ],
        ),
    ]
