# Generated by Django 2.0 on 2018-09-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0107_deviceuserextra'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('userId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('appId', models.IntegerField()),
                ('enabled', models.IntegerField()),
                ('updateTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'city_UserLocation',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='deviceuserextra',
            name='area_type',
            field=models.IntegerField(default=-1, help_text='0 - 主城区，1 - 县城，2 - 外地'),
        ),
        migrations.AlterField(
            model_name='deviceuserextra',
            name='lbs_flag',
            field=models.IntegerField(default=-1, verbose_name='是否打开gps'),
        ),
    ]
